version: '3'

services:
  gateway:
    container_name: 'emailhub-gateway'
    image: 'emailhub-gateway'
    build:
      context: .
      dockerfile: Gateway/Gateway.API/Dockerfile-slow-connection
    volumes:
      - .:/var/www/gateway
    ports:
      - '8001:80'
    networks:
      - emailhub-network
  
  emailprocessor:
    container_name: 'emailhub-emailprocessor'
    image: 'emailhub-emailprocessor'
    build:
      context: .
      dockerfile: EmailProcessor/EmailProcessor.Worker/Dockerfile-slow-connection
    volumes:
      - .:/var/www/emailprocessor
    ports:
      - '8002:80'
    networks:
      - emailhub-network

  logger:
    container_name: 'emailhub-logger'
    image: 'emailhub-logger'
    build:
      context: .
      dockerfile: Logger/Logger.Worker/Dockerfile-slow-connection
    volumes:
      - .:/var/www/logger
    ports:
      - '8003:80'
    depends_on:
      - 'db'
    networks:
      - emailhub-network

  db:
    container_name: 'postgres'
    image: postgres
    environment:
      - POSTGRES_PASSWORD=abuzafor73azf
    networks:
      - emailhub-network

networks:
  emailhub-network:
    driver: bridge